cargo-features = ["edition2021"]

[package]
name = "pkos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bootimage = "0.10.3"
bootloader = "0.11.0"
